# fly.toml app configuration file generated for gordle on 2024-01-24T08:39:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gordle"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[env]
  APP_ENV="prod"
  CGO_ENABLED=1
  GIN_MODE="debug"
  DATABASE_PROVIDER="postgres"
  CLIENT_ADDRESS = "https://atrokarvinen.github.io"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
